FROM python:3.9.10-alpine3.14

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . /app

RUN apk update && \
    apk add --no-cache libxml2-dev libxslt-dev python3-dev postgresql-dev gcc python3-dev musl-dev && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["python","manage.py","runserver","0.0.0.0:8000"]
